### ISSUE TITLE
The dropdown can be drawn outside of the window

### ISSUE THREAD

**Issue by hamoid** [roymacdonald/ofxDropdown#13]
If the component is near the bottom border of the window, the dropdown is not visible. I didn't test but the same might happen if the component is near the right edge of the window.

As a solution one could test for these conditions and make sure the dropdown is placed inside the visible area.

**Comment by roymacdonald** [comment]
yes. there is an option that allows you to choose at which side of the component you want the dropdown to be drawn. 
I did not add an automatic way for handling this, which might be useful.

**Comment by roymacdonald** [comment]
Call the following function on the dropdown instance and pass to it one of the options further down
```
setDropDownPosition(DropDownPosition pos);
		DD_RIGHT,
		DD_BELOW,
		DD_ABOVE,
		DD_LEFT	

```
