### ISSUE TITLE
how to refresh string dropdown list?

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxDropdown#17]
I understand how to fill the dropdown menu with values via the ->add function.

But what about changing / updating the content during run time? 

Right now I am testing.

```
 IP_strDropdown->clear();
        IP_strDropdown->add("offline");
        
        vector<string> ip_list = getLocalIPs();
        for(int i=0; i<ip_list.size(); i++){
            ofLog()<<ip_list[i];
            IP_strDropdown->add(ofTrim(ip_list[i]));
        }

        ofLog()<<"myIP "<<myIP<<" IP_strDropdown "<<IP_strDropdown->getDropdownParameters().size();
```

`IP_strDropdown->getDropdownParameters().size()` does report the updated size but the gui element does not show the new options.

thanks for your advice.

**Comment by stephanschulz** [comment]
I think ` IP_strDropdown->forceRedraw();` did the trick.

**Comment by roymacdonald** [comment]
well that is kinda annoying to have to destroy and rebuild every time.
maybe I could add a function like updateString(...) or something

**Comment by Jonathhhan** [comment]
@roymacdonald that would be great, I was searching for exactly that function...

**Comment by roymacdonald** [comment]
@Jonathhhan I just added that feature, along with a lot more. Check the ofxDropdown.h file, every function has inline documentation.
The ones for what you ask for are:
```
    bool setOptionNameByValue(const T& value, const string& newName);
    bool setOptionNameByIndex(const size_t& index, const string& newName);
    
    bool updateOptionName(const string& currentName, const string& newName);
```

**Comment by Jonathhhan** [comment]
@roymacdonald thanks. i guess, if the number of the options changes is the code from @stephanschulz a good way to go (I do not need to call it too often)? Edit: tested it, and it works very well with clearing...

**Comment by roymacdonald** [comment]
> IP_strDropdown->getDropdownParameters().size() does report the updated size but the gui element does not show the new options.

That usage is wrong. `getDropdownParameters()` gives you the parameterGRoup that holds the configuration options for the dropdown. If you want to get the number of options of the dropdown use `getNumOptions()`. Probably adding a 'size()' function could be a lot more intuitive.

It is correct to use the code that @stephanschulz  posted. I wouldn't call that on every frame as it it seems to be a bit overkill, rather only when needed.
