### ISSUE TITLE
Type 'ofParameter<ofFile>' does not provide a call operator

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxDropdown#18]
I am trying to use the `populateFromDirectory` example but am not able to query which item is current selected in the dropdown file selector.
I know I could use the listener to update an other string to hold the current file name. But ... 

![Screen Shot 2022-09-04 at 9 54 31 PM](https://user-images.githubusercontent.com/1054816/188345168-23eb4e95-33d6-45a4-b6bf-5c90360629e2.jpg)

**Comment by roymacdonald** [comment]
You need to call selectedValue.get() to access it.
