### ISSUE TITLE
Mouse scroll behaviour

### ISSUE THREAD

**Issue by Jonathhhan** [roymacdonald/ofxDropdown#19]
Not sure if this is intended, but with `ofxPanel` mousescrolled moves the options up and down the screen (with `ofxGuiGroup` nothing happens). I would rather expect scroll to change the preselected option (like with mouse move), so that you can select it with enter (for example), if not with clicking the option (that would be nice for `ofxGuiGroup`, too). Also, if I move the `ofxPanel`, the option do not move with it. And, is it possible to hide the option on "onmouseout", if the mouse leaves the `ofxPanel` / `ofxGuiGroup` or the selected option?
All the `ofxPanel` issues do not affect my case, because I use `ofxGuiGroup`, just wanted to mention it.

**Comment by Jonathhhan** [comment]
Hmm, now somehow the right border of the dropdown options is not shown.
![Screenshot from 2022-12-13 03-34-05](https://user-images.githubusercontent.com/41275844/207213275-ed66e3ac-34fa-4cd0-b15e-c26293b527ab.png)
Actually I do not need a right / left border at all, that would be consistent with the main options?
Or is there just that one border to mark the start of the dropdown menu?
That is the code of my attempt:
https://github.com/Jonathhhan/ofEmscriptenExamples/blob/main/dropdown_audio_select/src/ofApp.cpp

And another idea, would it be possible, that the options appear onmouseover and dissapear onmouseout, so no click would be needed to make them appear / disappear. That would be really handy, at least as an option (I tried to figure it out, but no luck...). Anyway, thanks for this very useful addon. One last question, is it possible to disable the collapse function without disabling the header of the gui?

**Comment by roymacdonald** [comment]
Hi. The scrolling behaviour is what I intended. I often end up with long list that go out of screen so scrolling is kinda needed. When scrolling I would assume that if the mouse is over the dropdown you can simply clic on the option you want.

It is strange that you have things behaving differently with ofxGuiGroup and ofxPanel, as the latter inherits from the former and the only addition to ofxPanel are the save and load buttons on the top right corner.

What you mention about not seeing the borders is an OF "bug" You can customize it though. There are a bunch of padding static variables in ofxBaseGui which control that thing. 

As of the idea of showing the dropdown on mouse over it is actually a nice one. It does not sound like a complex thing to implement at all, and I agree it could be quite handy.

> One last question, is it possible to disable the collapse function without disabling the header of the gui?

As far as I can recall, you cant without modifying ofxGui.

**Comment by roymacdonald** [comment]
BTW, as for your example. 
Check the ofxDropdown example_FolderFiles. It can auto populate the dropdown from a directory.

**Comment by Jonathhhan** [comment]
@roymacdonald hi, and thank you for the clarifications, that helps.
And sorry for naming that a bug, i just do not know `ofxGui` enough, I will check the variables out...
I had a look at the example, but I guess I will have a `std::vector<std::string>` for populating the menu (I will get a list of audio / midi devices from Java Script) and not files from a directory.

**Comment by roymacdonald** [comment]
@Jonathhhan no worries. Glad to help.
And it was me who named that a "bug". :D

So, you can also use an `std::map<std::string, std::string>` and pass that to the drop down, where the first value is "value" and the second is the string drawn in the dropdown. This way, for instance you can hold the full info of each audio midi device but just show a friendlier name.

You can also add elements to the dropdown without the vector or map, just one by one. It might be handier if you are actually populating the vector somehow and then passing it to the dropdown instance.

**Comment by Jonathhhan** [comment]
> So, you can also use an `std::map<std::string, std::string>` and pass that to the drop down, where the first value is "value" and the second is the string drawn in the dropdown. This way, for instance you can hold the full info of each audio midi device but just show a friendlier name.
> 
> You can also add elements to the dropdown without the vector or map, just one by one. It might be handier if you are actually populating the vector somehow and then passing it to the dropdown instance.

@roymacdonald 
Thank you, with webMidi that works pretty well (show the name and return the id).
I need to make a vector of the string anyway with ofSplitString(), so in my case it does not matter but good to know.
I populate it like that:
```
void loadMidiInDevices(std::string string){  
	std::vector<std::string> deviceList = ofSplitString(string, ",", true);      	
	midiInputDropdown->clear();
	for(int j = 0; j < deviceList.size(); j += 2){
		midiInputDropdown->add(deviceList[j], deviceList[j + 1]);
	}
	midiInputDropdown->forceRedraw();
}
```
Here is the example: https://github.com/Jonathhhan/ofEmscriptenExamples/tree/main/webmidi_draft

**Comment by roymacdonald** [comment]
@Jonathhhan That looks good. Glad that this addon is helpful

**Comment by Jonathhhan** [comment]
@roymacdonald yes, its really helpful. thank you. here is a demo: https://mtest.handmadeproductions.de/
Even if you connect / disconnect new devices the menu is updated nicely.
Only the onmouseover feature would be really great, too.
