### ISSUE TITLE
New version: Options position and darkened background

### ISSUE THREAD

**Issue by Jonathhhan** [roymacdonald/ofxDropdown#22]
Hey @roymacdonald.
Is it possible to disable the darkened background when options are shown?
And somehow the position of the options seems wrong(also in the FolderFiles example). Both is not an issue with the older version.
And sorry for my last issue, I was using the older version until now.
Here is a screenshot from the current version:
 
![Screenshot from 2022-12-18 21-03-01](https://user-images.githubusercontent.com/41275844/208317926-f536957c-beac-4bd7-ad82-42879a57c513.png)

**Comment by roymacdonald** [comment]
Ohh true. I added that feature but totally makes sense to have disabled by default and give the option to enable

**Comment by Jonathhhan** [comment]
Maybe I need to set something like `midiInputDropdown->setDropdownPosition(DD_RIGHT);`
for the position now?
But with exactly that I get:
```
error: use of undeclared identifier 'DD_RIGHT'
        midiInputDropdown->setDropDownPosition(DD_RIGHT);
```
Edit: if I set `DD_RIGHT` manually with
`group.setPosition(b.getMaxX(), b.y);`
the position is correct, I just do not know how to call `setDropDownPosition()`...

**Comment by roymacdonald** [comment]
I will fix asap. It is because I added an auto position, which is DD_AUTO and left as default. but I did not take into account the case you mention.

**Comment by roymacdonald** [comment]
Hi. I fixed this. 
thanks for letting me know.
now it should behave as it was before

**Comment by Jonathhhan** [comment]
@roymacdonald great, thank you :)
