### ISSUE TITLE
Load settings

### ISSUE THREAD

**Issue by joaoffreire** [roymacdonald/ofxDropdown#24]
When I load the settings, the correct options appear selected, however the function getAllSelected() return empty (for fields that allow multi selection) and channels[i].get()->selectedValue also return empty. I have to click on the highlighted selection for it to be returned. 

```
for(int i = 0; i < 24; i++)
    {
        unique_ptr<ofxIntDropdown> aux;
        aux = make_unique<ofxIntDropdown>("Fixture "+ ofToString(i+1));
        aux->disableMultipleSelection();
        aux->enableCollapseOnSelection();
        channels.push_back(std::move(aux));
    }
    unique_ptr<ofxIntDropdown> aux;
    aux = make_unique<ofxIntDropdown>("Grouping "+ ofToString(1));
    aux->enableMultipleSelection();
    aux->disableCollapseOnSelection();
    channels.push_back(std::move(aux));

```
This is how i'm creating and adding the options to the panel.

**Comment by roymacdonald** [comment]
Hi, 
thanks for letting mi know.
I will check that, as the getAllSelected function returns a cached vector, so it is not needed to get filled each time you call it, although selectedVAlue should hold something.

**Comment by johnnyboss** [comment]
Sorry to get back to this but this is driving me insane. Even running your example doesn't load the settings on startup. I always have to click the dropdown menu again for it to load correctly. 
This: ofDrawBitmapStringHighlight(ofToString(intOptions.get()), 20, ofGetHeight() - 50);
Always return a random value until I reselect an option. Shouldn't it just load from the settings and accept the loaded value?

**Comment by roymacdonald** [comment]
Hi @johnnyboss are you actually loading the gui settings from a file at startup? I ask because it does not happen automatically. Thus you need to explicitly call for such. 
`gui.loadFromFile("settings.json");//or whichever file you want to load from`
Make sure you call it after you have setup all the gui and dropdowns.

**Comment by johnnyboss** [comment]
![Screenshot from 2023-01-07 13-57-09](https://user-images.githubusercontent.com/288941/211154418-6f5d10aa-0621-4906-ae23-f72dbe7ae098.png)
As you can see the option loaded is 11 but on the bottom it's an undefined value. This is from your example and I added the 
gui.loadFromFile("DropdownsSettings.json");
on the last line of the setup()

**Comment by roymacdonald** [comment]
That's odd. It does not happen to me. Is that just the example? Which OF version are you using? Plattform, is ofxDropdown the newest commit?

**Comment by johnnyboss** [comment]
I was in the previous commit. Updating it seems to have solved the problem. I'll close it thank you.
