### ISSUE TITLE
clear() does not seem to work

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxDropdown#26]
It seems that calling  ->clear() does not remove previous list items.
In my case the list of available NDI devices only becomes available after the app has been running for a few seconds and might actually change over time when new devices come online.

So I thought to check if the amount of items in the dropdown list is different than the available cameras and update the list accordingly. But the below code does not do that :(

ndi_strDropdown->getNumOptions() does not become zero when calling ndi_strDropdown->clear()

?
```
void setupDropdown(){
       
        ndi_strDropdown.clear();
        //get back a list of devices.
        ofLog()<<"setupDropdown() pre: ndi_strDropdown->getNumOptions() "<<ndi_strDropdown->getNumOptions();
        for(int i = 0; i < ndiReceiver.GetSenderCount(); i++){
            ofLog()<<i<<" ndiReceiver.GetSenderName(i) "<<ndiReceiver.GetSenderName(i);
            ndi_strDropdown->add(ndiReceiver.GetSenderName(i), ndiReceiver.GetSenderName(i));
        }
        
        ofLog()<<"setupDropdown() post: ndi_strDropdown->getNumOptions() "<<ndi_strDropdown->getNumOptions();
    }

```

**Comment by roymacdonald** [comment]
HI @stephanschulz 
I just pushed a change which should help you.
