### ISSUE TITLE
what is the best strategy to fill a list after setup is done.

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxDropdown#27]
I populate the dropdown list with a bunch of detected network camera NDI IPs. It takes a few seconds after running the app for all cameras to announce themselves. This means I can not populate the dropdown list during setup because I do not know their IPs yet.
But I do need to supply an NDI name or index in order for the ofxNDI addon to initialize. 

I guess I am asking if I need to use a 2nd ofParameter to store the most current dropdown list selects so that I can use this value during the next app start up, since the dropdown list is not yet filled?

**Comment by roymacdonald** [comment]
Hi, The dropdown current value is stored in an ofParameter. It is called selectedValue. If you setup or initialize the dripdown passing an ofParameter it will be referenced to the deopdown's selectedValue parameter. So, when you save the Gui this parameter is what gets saved.

But as for filling the dripdown I would recommend you to listen to the dropdown's dropdownWillShow_E event. This event is called right after you click to open the dropdown but before showing anything. This allows you to populate the dropdown when this event is called, so you can update it dynamically each time you open it. I can make an example if you want

**Comment by stephanschulz** [comment]
thanks.
for my own future self

in setup() I add ``` ofAddListener(ndi_strDropdown->dropdownWillShow_E, this, &ndiCamera::dropdownNotified);```

and then create a function called ` void dropdownNotified()`
