### ISSUE TITLE
addListener does not get triggered on deselect and getAllSelected() does not update

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxDropdown#28]
when selecting a string option the attached listener does not get called.
also using the keyboard to check `strDropdown->getAllSelected()` still shows the deselected option.

https://gist.github.com/stephanschulz/ea730b9ad76f6ef94a3a69d4371579a6

**Comment by roymacdonald** [comment]
I am not sure. I have not used this one for a while. I'll check and let you know

**Comment by roymacdonald** [comment]
@stephanschulz I just pushed and I think that now it works properly. Please check if it works as you were intending.
