### ISSUE TITLE
dropdown not loading 1st list item

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxDropdown#29]
I am filling a string dropdown list with two strings.

when the app starts I need the previously selected dropdown element to be loaded.
this works fine as long as I do not selected the first listed item.
in my case Enttec Usb will never get selected on app start, but artnet works fine.

would you know why?

here the dropdown successfully loaded the 2nd element:
![Screenshot 2024-12-04 at 6 28 07 PM](https://github.com/user-attachments/assets/39913524-9008-4efc-8b67-f59df050eedb)

but if I selected the 1st element it will not be loaded:
![Screenshot 2024-12-04 at 6 28 12 PM](https://github.com/user-attachments/assets/13b1b8f9-398a-4ba1-906a-de7d5161e55f)

```
 device_selected.setName("selected dmx device");
        device_strDropdown = make_unique<ofxDropdown>(device_selected);

        device_strDropdown->disableMultipleSelection();
        device_strDropdown->enableCollapseOnSelection();

        device_strDropdown->add("Enttec USB");
        device_strDropdown->add("Artnet IP");
         device_strDropdown->forceRedraw();

        gui_dmx.add(device_strDropdown.get());
        ofLog() << "dmx device_selected " << device_selected.get();


        gui_dmx.add(group_artnet);
        
        ```

**Comment by stephanschulz** [comment]
correction only the last element gets loaded. all others leave the dropdown gui element blank

https://github.com/user-attachments/assets/3d417928-da89-4ce1-ab94-4a7c516491ed

**Comment by roymacdonald** [comment]
I remember seeing a similar issue last year, which I fixed.I'll check it.

**Comment by roymacdonald** [comment]
Hi @stephanschulz 
I just made a commit which should fix this issue. Let me know if it works for you.

**Comment by stephanschulz** [comment]
thank you. it works now.
