### ISSUE TITLE
Values of the dropdown do not get loaded when calling gui.loadFromFile

### ISSUE THREAD

**Issue by edap** [roymacdonald/ofxDropdown#5]
Hello Roy, I am currently using this addon and I have noticed that when calling `gui.saveToFile(myFile)` the selected option is correctly saved, but when calling `gui.loadFromFile(myFile)` the selected option saved in the file it is not reflected in the GUI, as it is happening for the other parameters.

**Comment by roymacdonald** [comment]
Hi Davide.
Thanks for letting me know.
I will check asap.
cheers

**Comment by roymacdonald** [comment]
@edap I just pushed an update. but I think it still needs a bit more of work. let me know if this works for you. 
all the best

**Comment by edap** [comment]
Many thanks Roy, it works. There is some ofLog() left somewhere I suppose, as I see `ofxDropdown_<T>::generateDraw()` in the console, but it doesn’t matter, it works fine for me.

**Comment by roymacdonald** [comment]
Hi @edap , sorry for that I fixed it and pushed. Also I was not setting the dropdown value when loading, it was just showing the loaded name in the gui but not in the dropdown. Now it is fixed.
cheers
