### ISSUE TITLE
disableHeader member missing from ofxGuiGroup

### ISSUE THREAD

**Issue by timredfern** [roymacdonald/ofxDropdown#7]
openFrameworks/addons/ofxDropdown/src/ofxDropdown.cpp:46:8: error: no member named
      'disableHeader' in 'ofxGuiGroup'
        group.disableHeader();
        ~~~~~ ^
what version of ofxGui (ie of openframeworks) does ofxDropdown compile against?

**Comment by roymacdonald** [comment]
Hi! It works with the current github master or patch-release branches or the newest nightly build. You can find the latter at openframeworks.cc/download/ and scroll down towards the end of that page.

**Comment by timredfern** [comment]
hmm, github master and patch-release aren't building for me on OSX at present but the nightly build does, Thanks!

**Comment by roymacdonald** [comment]
Hi, with the github versions you need to run the following script `your_openframeworks_dir/scripts/dev/download_libs.sh`other wise it will not build in general.

**Comment by timredfern** [comment]
Ah yes, you're right!

I had previously been using the github release - dunno how to tell if the libs needs redownloading - first thing to check I guess?

**Comment by roymacdonald** [comment]
the libs need to be redownloaded if any change was made to the included additional libraaries.
One option is to look at the commit history and determine if such happened. THe other option and way much easier and ffaster si to simply run the script and redownload.
best
