### ISSUE TITLE
Compiling on Linux

### ISSUE THREAD

**Issue by AnasGhrab** [roymacdonald/ofxDropdown#8]
When I try the example-basic on Ubuntu, I get this : 

```
In file included from /home/anas/of_v0.11.0_linux64gcc6_release/addons/ofxDropdown/example_Basic/src/ofApp.h:5,
                 from /home/anas/of_v0.11.0_linux64gcc6_release/addons/ofxDropdown/example_Basic/src/main.cpp:2:
/home/anas/of_v0.11.0_linux64gcc6_release/addons/ofxDropdown/src/ofxDropdown.h: In instantiation of ‘class ofxDropdown_<std::__cxx11::basic_string<char> >’:
/usr/include/c++/9/bits/unique_ptr.h:79:16:   required from ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = ofxDropdown_<std::__cxx11::basic_string<char> >]’
/usr/include/c++/9/bits/unique_ptr.h:292:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = ofxDropdown_<std::__cxx11::basic_string<char> >; _Dp = std::default_delete<ofxDropdown_<std::__cxx11::basic_string<char> > >]’
/home/anas/of_v0.11.0_linux64gcc6_release/addons/ofxDropdown/example_Basic/src/ofApp.h:6:7:   required from here
/home/anas/of_v0.11.0_linux64gcc6_release/addons/ofxDropdown/src/ofxDropdown.h:129:7: error: ‘void ofxDropdown_<T>::registerMouseEvents() [with T = std::__cxx11::basic_string<char>]’ marked ‘override’, but does not override
  129 |  void registerMouseEvents() override;
      |       ^~~~~~~~~~~~~~~~~~~
/home/anas/of_v0.11.0_linux64gcc6_release/addons/ofxDropdown/src/ofxDropdown.h:130:7: error: ‘void ofxDropdown_<T>::unregisterMouseEvents() [with T = std::__cxx11::basic_string<char>]’ marked ‘override’, but does not override
  130 |  void unregisterMouseEvents() override;
      |       ^~~~~~~~~~~~~~~~~~~~~
/home/anas/of_v0.11.0_linux64gcc6_release/addons/ofxDropdown/src/ofxDropdown.h: In instantiation of ‘class ofxDropdown_<int>’:
/usr/include/c++/9/bits/unique_ptr.h:79:16:   required from ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = ofxDropdown_<int>]’
/usr/include/c++/9/bits/unique_ptr.h:292:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = ofxDropdown_<int>; _Dp = std::default_delete<ofxDropdown_<int> >]’
/home/anas/of_v0.11.0_linux64gcc6_release/addons/ofxDropdown/example_Basic/src/ofApp.h:6:7:   required from here
/home/anas/of_v0.11.0_linux64gcc6_release/addons/ofxDropdown/src/ofxDropdown.h:129:7: error: ‘void ofxDropdown_<T>::registerMouseEvents() [with T = int]’ marked ‘override’, but does not override
  129 |  void registerMouseEvents() override;
      |       ^~~~~~~~~~~~~~~~~~~
/home/anas/of_v0.11.0_linux64gcc6_release/addons/ofxDropdown/src/ofxDropdown.h:130:7: error: ‘void ofxDropdown_<T>::unregisterMouseEvents() [with T = int]’ marked ‘override’, but does not override
  130 |  void unregisterMouseEvents() override;
      |       ^~~~~~~~~~~~~~~~~~~~~
Process failed with exit code 1.
```

**Comment by roymacdonald** [comment]
Hi, you shouldn't get that error.
make sure you have the current version of openFrameworks.

Just in case,
if you look in `your_openFrameworks_folder/addons/ofxGui/src/ofxBaseGui.h` you should see the two following functions declared as virtual
```
	virtual void registerMouseEvents();
	virtual void unregisterMouseEvents();

```
If this is not like this it is probably because you have an old version.

**Comment by UrielGuy** [comment]
Hey. Having the same problem on windows.
When using the official 0.11.0 release from https://openframeworks.cc/download/ these functions are not virtual. 
Looks like these were made virtual in the last commit to this file, which while was in february 2020, wasn't released yet.

**Comment by roymacdonald** [comment]
@UrielGuy Hi yes, those were made virtual after the 0.11.0 release. You can download the latest nightly build, these are in https://openframeworks.cc/download/ , just scroll down to the bottom of the page and it should work. Or, you can make these functions virtual on your own openFrameworks files, just add the virtual keyword in front of the funtion declarations in the ofxBaseGui.h file, and recompile. (ofxGui is an addon so it wont be recompiling or modifying the core).
let me know if it works.
Also, I have not tested yet but I was told that on windows there was another compiling issue related to the toString function on my addon. Can you see if that is correct please? I dont have a window at hand ATM.

**Comment by UrielGuy** [comment]
It is true. It's related to the directory drop down list, so I've just removed all of that for now as I don't use it, but happy to help resolve the issue. I think it says that there's no << operator for ofFile, but I'm not next to the right computer right now to verify.

**Comment by UrielGuy** [comment]
The compilation on windows fails (with version 0.11 official release) because there is no << operator for ofFile. 
The line in fault is:
```
ofxDropdown\src\ofxDropdown.cpp(165): message : see reference to class template instantiation 'ofxDropdown_<ofFile>' being compiled
```

**Comment by hamoid** [comment]
I could run the example fine on Ubuntu, openFrameworks from git.
