### ISSUE TITLE
Windows '<<': no operator found which for typedef ofxDropdown_<ofFile>

### ISSUE THREAD

**Issue by pierrextardif** [roymacdonald/ofxDropdown#9]
Hi,

Thanks for the addon Roy!
As referenced [here](https://github.com/roymacdonald/ofxDropdown/issues/8#issuecomment-776807427), windows doesn't understand the operator `<<` for `ofFile` .
Not a big deal in my case, just commented out the relevant code ( ofxDropdpwn::addFromDir and ofxDropdown::addFromDir ), but it would be nice to add it to the OF source code for windows?

**Comment by Empyreans** [comment]
When I'm trying to use this addon on windows I too get such an error with `ofToString`:

`Error	C2678	binary '<<': no operator found which takes a left-hand operand of type 'std::ostringstream' (or there is no acceptable conversion)	ImageProcessingTool	C:[...]\of\libs\openFrameworks\utils\ofUtils.h	662`

**Comment by roymacdonald** [comment]
Hi. It is the same error that has been commented. On the meanwhile just comment out the relevant code. I will add an ifdef to disable it for windows.

**Comment by roymacdonald** [comment]
Hi @Empyreans I just pushed an update that should fix this issue. It is just a workaround but you still should get full functionality from this addon. Let me know if it works on Windows. (I don't have a windows machine at hand for testing)

**Comment by pierrextardif** [comment]
should be working [here](https://github.com/roymacdonald/ofxDropdown/pull/14):
`ofRegisterMouseEvents` isn't working on windows 10.
